version: "3"

services:
  fcrepo:
    image: fcrepo/fcrepo:6.1.1
    ports:
      - 8082:8080
      - 61616:61616
    volumes:
        - fcrepo-home:/usr/local/tomcat/fcrepo-home
    environment:
      CATALINA_OPTS: "-Dfcrepo.jms.baseUrl=http://fcrepo:8080"

volumes:
  fcrepo-home:
