<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.fedora.info/definitions/1/0/access/" 
            xmlns="http://www.fedora.info/definitions/1/0/access/"
            xmlns:apim="http://www.fedora.info/definitions/1/0/management/"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            elementFormDefault="qualified">
    <xsd:import namespace="http://www.fedora.info/definitions/1/0/management/"
                schemaLocation="datastreamProfile.xsd" />
	<!-- root element declaration -->
	<xsd:element name="objectDatastreams">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="objectDatastreamsType"/>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<!-- complex type declarations -->
	<xsd:complexType name="objectDatastreamsType">
	    <xsd:choice minOccurs="0" maxOccurs="1">
		    <xsd:sequence>
			    <xsd:element name="datastream" type="datastreamType" minOccurs="0" maxOccurs="unbounded"/>
		    </xsd:sequence>
		    <xsd:sequence>
			    <xsd:element name="datastreamProfile" type="apim:datastreamProfile" minOccurs="0" maxOccurs="unbounded"/>
		    </xsd:sequence>
	    </xsd:choice>
		<xsd:attribute name="pid" type="xsd:string" use="required"/>
		<xsd:attribute name="asOfDateTime" type="xsd:string" use="optional"/>
		<xsd:attribute name="baseURL" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="datastreamType">
		<xsd:attribute name="dsid" type="xsd:string" use="required"/>
		<xsd:attribute name="label" type="xsd:string" use="required"/>
		<xsd:attribute name="mimeType" type="xsd:string" use="required"/>
	</xsd:complexType>
</xsd:schema>
